import { Lineup, Artist, Gig } from "../../models/index.js"

class LineupSeeder {
  static async seed(){
    const zola = await Artist.query().findOne("artistName", "ZOLA")
    const porter = await Artist.query().findOne("artistName", "Porter Robinson")
    const skrillex = await Artist.query().findOne("artistName", "Skrillex")
    const gecs = await Artist.query().findOne("artistName", "100 Gecs")
    const xandor = await Artist.query().findOne("artistName", "Xandor")
    const protohype = await Artist.query().findOne("artistName", "Protohype")
    const formerHero = await Artist.query().findOne("artistName", "Former Hero")
    const hexCougar = await Artist.query().findOne("artistName", "Hex Cougar")
    const shadient = await Artist.query().findOne("artistName", "Shadient")
    const tisoki = await Artist.query().findOne("artistName", "Tisoki")
    const fluxPavilion = await Artist.query().findOne("artistName", "Flux Pavilion")
    const rlGrime = await Artist.query().findOne("artistName", "RL Grime")
    const oliverse = await Artist.query().findOne("artistName", "Oliverse")
    const slushii = await Artist.query().findOne("artistName", "Slushii")
    const ghastly = await Artist.query().findOne("artistName", "GHASTLY")
    const muraMasa = await Artist.query().findOne("artistName", "Mura Masa")
    const baynk = await Artist.query().findOne("artistName", "BAYNK")
    const fourb = await Artist.query().findOne("artistName", "4B")
    const papaKhan = await Artist.query().findOne("artistName", "Papa Khan")
    const flume = await Artist.query().findOne("artistName", "Flume")
    const boombox = await Artist.query().findOne("artistName", "Boombox Cartel")
    const rossy = await Artist.query().findOne("artistName", "Rossy")
    const sanHolo = await Artist.query().findOne("artistName", "San Holo")
    const dabin = await Artist.query().findOne("artistName", "Dabin")
    const fred = await Artist.query().findOne("artistName", "Fred again...")
    const slowMagic = await Artist.query().findOne("artistName", "Slow Magic")
    const whethan = await Artist.query().findOne("artistName", "Whethan")
    const louis = await Artist.query().findOne("artistName", "Louis The Child")
    const biicla = await Artist.query().findOne("artistName", "Biicla")
    const zedsDed = await Artist.query().findOne("artistName", "Zed's Dead")
    const pauline = await Artist.query().findOne("artistName", "Pauline Herr")
    
    const midwxst = await Artist.query().findOne("artistName", "midwxst")
    const juiceWrld = await Artist.query().findOne("artistName", "Juice WRLD")
    const lilUziVert = await Artist.query().findOne("artistName", "Lil Uzi Vert")
    const kota = await Artist.query().findOne("artistName", "KOTA The Friend")
    const aidan = await Artist.query().findOne("artistName", "347 Aidan")
    const yungLean = await Artist.query().findOne("artistName", "Yung Lean")
    const kennyBeats = await Artist.query().findOne("artistName", "Kenny Beats")
    const pmp = await Artist.query().findOne("artistName", "PMP")
    const trippz = await Artist.query().findOne("artistName", "Trippz Michaud")
    const ericdoa = await Artist.query().findOne("artistName", "ericdoa")
    const chance = await Artist.query().findOne("artistName", "Chance The Rapper")


    const coachella = await Gig.query().findOne("name", "Coachella")
    const hardSummer = await Gig.query().findOne("name", "Hard Summer")
    const electricZoo = await Gig.query().findOne("name", "Electric Zoo")
    const campBisco = await Gig.query().findOne("name", "Camp Bisco")
    const rollingLoud = await Gig.query().findOne("name", "Rolling Loud")
    const lightningInABottle = await Gig.query().findOne("name", "Lightning in a Bottle")
    const dreamstate = await Gig.query().findOne("name", "Dreamstate")
    const edc = await Gig.query().findOne("name", "Electric Daisy Carnival")
    const globalDance = await Gig.query().findOne("name", "Global Dance Festival")
    const govBall = await Gig.query().findOne("name", "Governor's Ball")
    const beyondWonder = await Gig.query().findOne("name", "Beyond Wonderland")
    const imagine = await Gig.query().findOne("name", "Imagine Music Festival")
    const bonnaroo = await Gig.query().findOne("name", "Bonnaroo")
    const austinLimits = await Gig.query().findOne("name", "Austin City Limits")
    const lollapalooza = await Gig.query().findOne("name", "Lollapalooza")

    await Lineup.query().insert({gigId: coachella.id, artistId: zola.id})
    await Lineup.query().insert({gigId: coachella.id, artistId: xandor.id})
    await Lineup.query().insert({gigId: coachella.id, artistId: skrillex.id})
    await Lineup.query().insert({gigId: coachella.id, artistId: flume.id})
    await Lineup.query().insert({gigId: coachella.id, artistId: boombox.id})
    await Lineup.query().insert({gigId: coachella.id, artistId: porter.id})
    await Lineup.query().insert({gigId: coachella.id, artistId: oliverse.id})
    await Lineup.query().insert({gigId: coachella.id, artistId: yungLean.id})
    await Lineup.query().insert({gigId: coachella.id, artistId: tisoki.id})
    await Lineup.query().insert({gigId: coachella.id, artistId: kota.id})
    await Lineup.query().insert({gigId: coachella.id, artistId: ghastly.id})
    await Lineup.query().insert({gigId: coachella.id, artistId: lilUziVert.id})
    await Lineup.query().insert({gigId: coachella.id, artistId: aidan.id})
    await Lineup.query().insert({gigId: coachella.id, artistId: fluxPavilion.id})
    await Lineup.query().insert({gigId: coachella.id, artistId: gecs.id})
    await Lineup.query().insert({gigId: coachella.id, artistId: midwxst.id})

    await Lineup.query().insert({gigId: campBisco.id, artistId: porter.id})
    await Lineup.query().insert({gigId: campBisco.id, artistId: shadient.id})
    await Lineup.query().insert({gigId: campBisco.id, artistId: xandor.id})
    await Lineup.query().insert({gigId: campBisco.id, artistId: oliverse.id})
    await Lineup.query().insert({gigId: campBisco.id, artistId: zola.id})
    await Lineup.query().insert({gigId: campBisco.id, artistId: baynk.id})

    await Lineup.query().insert({gigId: rollingLoud.id, artistId: midwxst.id})
    await Lineup.query().insert({gigId: rollingLoud.id, artistId: kota.id})
    await Lineup.query().insert({gigId: rollingLoud.id, artistId: yungLean.id})
    await Lineup.query().insert({gigId: rollingLoud.id, artistId: lilUziVert.id})
    await Lineup.query().insert({gigId: rollingLoud.id, artistId: juiceWrld.id})
    await Lineup.query().insert({gigId: rollingLoud.id, artistId: pmp.id})
    await Lineup.query().insert({gigId: rollingLoud.id, artistId: trippz.id})
    await Lineup.query().insert({gigId: rollingLoud.id, artistId: kennyBeats.id})
    await Lineup.query().insert({gigId: rollingLoud.id, artistId: chance.id})
    await Lineup.query().insert({gigId: rollingLoud.id, artistId: ericdoa.id})

    await Lineup.query().insert({gigId: hardSummer.id, artistId: skrillex.id})
    await Lineup.query().insert({gigId: hardSummer.id, artistId: tisoki.id})
    await Lineup.query().insert({gigId: hardSummer.id, artistId: oliverse.id})
    await Lineup.query().insert({gigId: hardSummer.id, artistId: slushii.id})
    await Lineup.query().insert({gigId: hardSummer.id, artistId: ghastly.id})

    await Lineup.query().insert({gigId: electricZoo.id, artistId: porter.id})
    await Lineup.query().insert({gigId: electricZoo.id, artistId: protohype.id})
    await Lineup.query().insert({gigId: electricZoo.id, artistId: oliverse.id})
    await Lineup.query().insert({gigId: electricZoo.id, artistId: shadient.id})
    await Lineup.query().insert({gigId: electricZoo.id, artistId: skrillex.id})

    await Lineup.query().insert({gigId: lightningInABottle.id, artistId: formerHero.id})
    await Lineup.query().insert({gigId: lightningInABottle.id, artistId: hexCougar.id})
    await Lineup.query().insert({gigId: lightningInABottle.id, artistId: xandor.id})
    await Lineup.query().insert({gigId: lightningInABottle.id, artistId: zola.id})
    await Lineup.query().insert({gigId: lightningInABottle.id, artistId: gecs.id})
    await Lineup.query().insert({gigId: lightningInABottle.id, artistId: oliverse.id})
    await Lineup.query().insert({gigId: lightningInABottle.id, artistId: fluxPavilion.id})

    
    await Lineup.query().insert({gigId: dreamstate.id, artistId: skrillex.id})
    await Lineup.query().insert({gigId: dreamstate.id, artistId: tisoki.id})
    await Lineup.query().insert({gigId: dreamstate.id, artistId: zola.id})
    await Lineup.query().insert({gigId: dreamstate.id, artistId: shadient.id})
    await Lineup.query().insert({gigId: dreamstate.id, artistId: porter.id})

    
    await Lineup.query().insert({gigId: edc.id, artistId: protohype.id})
    await Lineup.query().insert({gigId: edc.id, artistId: xandor.id})
    await Lineup.query().insert({gigId: edc.id, artistId: oliverse.id})
    await Lineup.query().insert({gigId: edc.id, artistId: fourb.id})
    await Lineup.query().insert({gigId: edc.id, artistId: rlGrime.id})
    await Lineup.query().insert({gigId: edc.id, artistId: baynk.id})
    
    
    await Lineup.query().insert({gigId: globalDance.id, artistId: hexCougar.id})
    await Lineup.query().insert({gigId: globalDance.id, artistId: whethan.id})
    await Lineup.query().insert({gigId: globalDance.id, artistId: louis.id})
    await Lineup.query().insert({gigId: globalDance.id, artistId: flume.id})
    await Lineup.query().insert({gigId: globalDance.id, artistId: ghastly.id})
    await Lineup.query().insert({gigId: globalDance.id, artistId: fred.id})
    await Lineup.query().insert({gigId: globalDance.id, artistId: porter.id})
    await Lineup.query().insert({gigId: globalDance.id, artistId: fourb.id})
    
    
    await Lineup.query().insert({gigId: govBall.id, artistId: skrillex.id})
    await Lineup.query().insert({gigId: govBall.id, artistId: oliverse.id})
    await Lineup.query().insert({gigId: govBall.id, artistId: tisoki.id})
    await Lineup.query().insert({gigId: govBall.id, artistId: porter.id})
    await Lineup.query().insert({gigId: govBall.id, artistId: midwxst.id})
    await Lineup.query().insert({gigId: govBall.id, artistId: kota.id})
    await Lineup.query().insert({gigId: govBall.id, artistId: lilUziVert.id})
    await Lineup.query().insert({gigId: govBall.id, artistId: aidan.id})
    await Lineup.query().insert({gigId: govBall.id, artistId: zola.id})
    await Lineup.query().insert({gigId: govBall.id, artistId: xandor.id})
    await Lineup.query().insert({gigId: govBall.id, artistId: ghastly.id})
    
    
    await Lineup.query().insert({gigId: beyondWonder.id, artistId: baynk.id})
    await Lineup.query().insert({gigId: beyondWonder.id, artistId: fourb.id})
    await Lineup.query().insert({gigId: beyondWonder.id, artistId: skrillex.id})
    await Lineup.query().insert({gigId: beyondWonder.id, artistId: slushii.id})
    await Lineup.query().insert({gigId: beyondWonder.id, artistId: ghastly.id})
    await Lineup.query().insert({gigId: beyondWonder.id, artistId: porter.id})
    await Lineup.query().insert({gigId: beyondWonder.id, artistId: fluxPavilion.id})
    await Lineup.query().insert({gigId: beyondWonder.id, artistId: muraMasa.id})
    await Lineup.query().insert({gigId: beyondWonder.id, artistId: tisoki.id})
    
    
    await Lineup.query().insert({gigId: imagine.id, artistId: hexCougar.id})
    await Lineup.query().insert({gigId: imagine.id, artistId: rossy.id})
    await Lineup.query().insert({gigId: imagine.id, artistId: sanHolo.id})
    await Lineup.query().insert({gigId: imagine.id, artistId: dabin.id})
    await Lineup.query().insert({gigId: imagine.id, artistId: biicla.id})
    await Lineup.query().insert({gigId: imagine.id, artistId: zedsDed.id})
    await Lineup.query().insert({gigId: imagine.id, artistId: pauline.id})
    await Lineup.query().insert({gigId: imagine.id, artistId: whethan.id})
    
    
    await Lineup.query().insert({gigId: bonnaroo.id, artistId: whethan.id})
    await Lineup.query().insert({gigId: bonnaroo.id, artistId: papaKhan.id})
    await Lineup.query().insert({gigId: bonnaroo.id, artistId: rossy.id})
    await Lineup.query().insert({gigId: bonnaroo.id, artistId: pauline.id})
    await Lineup.query().insert({gigId: bonnaroo.id, artistId: dabin.id})
    await Lineup.query().insert({gigId: bonnaroo.id, artistId: slowMagic.id})
    await Lineup.query().insert({gigId: bonnaroo.id, artistId: fred.id})
    
    
    await Lineup.query().insert({gigId: austinLimits.id, artistId: skrillex.id})
    await Lineup.query().insert({gigId: austinLimits.id, artistId: hexCougar.id})
    await Lineup.query().insert({gigId: austinLimits.id, artistId: whethan.id})
    await Lineup.query().insert({gigId: austinLimits.id, artistId: rossy.id})
    await Lineup.query().insert({gigId: austinLimits.id, artistId: pauline.id})
    await Lineup.query().insert({gigId: austinLimits.id, artistId: papaKhan.id})
    await Lineup.query().insert({gigId: austinLimits.id, artistId: dabin.id})
    await Lineup.query().insert({gigId: austinLimits.id, artistId: fred.id})
    await Lineup.query().insert({gigId: austinLimits.id, artistId: zola.id})
    await Lineup.query().insert({gigId: austinLimits.id, artistId: trippz.id})
    await Lineup.query().insert({gigId: austinLimits.id, artistId: flume.id})


    await Lineup.query().insert({gigId: lollapalooza.id, artistId: skrillex.id})
    await Lineup.query().insert({gigId: lollapalooza.id, artistId: yungLean.id})
    await Lineup.query().insert({gigId: lollapalooza.id, artistId: midwxst.id})
    await Lineup.query().insert({gigId: lollapalooza.id, artistId: whethan.id})
    await Lineup.query().insert({gigId: lollapalooza.id, artistId: rossy.id})
    await Lineup.query().insert({gigId: lollapalooza.id, artistId: pauline.id})
    await Lineup.query().insert({gigId: lollapalooza.id, artistId: papaKhan.id})
    await Lineup.query().insert({gigId: lollapalooza.id, artistId: dabin.id})




    console.log("Lineups seeded")
  }
}

export default LineupSeeder
